baseURL = 'https://dalatcoder.github.io/'
languageCode = 'vi-vn'
title = 'NTH Blog'
theme = "ananke"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Hieu Nguyen Trong"
  favicon = ""
  site_logo = ""
  description = "Hieu Nguyen Trong personal blog"
  background_color_class = "bg-black"
  recent_posts_number = 3
  body_classes = "avenir bg-near-white"
  post_content_classes = "helvetica"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/DalatCoder"
